CREATE TABLE [dbo].[User]
(
	[Id]			INT IDENTITY NOT NULL,
	[UserName]		VARCHAR(250) NOT NULL,
	[Password]		VARCHAR(250) NOT NULL,

	CONSTRAINT PK_User PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT FK_User_Person FOREIGN KEY ([Id]) REFERENCES dbo.[Person]([Id])
)
